package objetos;

public interface Constantes {
	int CANTIDADSUBGRUPOS = 20;
	int TAMANOSUBGRUPOLETRAS = 10;
	int TAMANOSUBGRUPONUMERO = 5;
	int TANDASAPRENDIZAJE = 5;
	int COMBSUBGRUPOS = 15;
	int MAXINTENTOS = 270;
	String TEXTOENCRIPTADO = "xZwM7BWIpSjYyGFr9rhpEa+cYVtACW7yQKmyN6OYSCv0ZEg9jWbc6lKzzCxRSSIvOvli"
			+ "mQZBMZOYnOwiA9yy3YU8zk4abFSItoW6Wj0ufQ0=";
	int LETRA = 0;
	int NUMERO = 1;
}
